server:
  port: 9000

cloud:
  eureka-host: localhost
  zipkin-host: localhost

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:auth-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  zipkin:
    baseUrl: http://${cloud.zipkin-host}:9411
    sleuth:
      sampler:
        percentage: 1

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

management:
  endpoints:
    enable-by-default: true

    web:
      exposure:
        include: "*"
