telegram:
  botName: java-micro-notification
  token: 6787552943:AAHR9dG3-_sxGhUtEJqWzHWTpa7DMOJ92kM

server:
  port: 8020

cloud:
  kafka-host: localhost
  eureka-host: localhost
  access-token-url: http://localhost:9000/oauth/token
  user-info-url: http://localhost:9000/user

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: notification-bot

  kafka:
    consumer:
      bootstrap-servers: ${cloud.kafka-host}:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

security:
  oauth2:
    resource:
      user-info-url: ${cloud.user-info-url}
    client:
      access-token-url: ${cloud.access-token-url}
      client-id: notification
      client-secret: notification123
