server:
  port: 8085

cloud:
  eureka-host: localhost
  logstash-host: localhost
  zipkin-host: localhost

spring:
  application:
    name: currency-rate-service

  zipkin:
    baseUrl: http://${cloud.zipkin-host}:9411
    sleuth:
      sampler:
        percentage: 1

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

logstash:
  enabled: false
  host: ${cloud.logstash-host}

currency:
  client:
    url: "http://cbr.ru/scripts/XML_daily.asp"

management:
  endpoints:
    enable-by-default: true

    web:
      exposure:
        include: "*"
