global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'currency-service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['172.17.0.1:8086']

  - job_name: 'currency-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ '172.17.0.1:8087' ]

  - job_name: 'processing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ '172.17.0.1:8090' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ '172.17.0.1:9000' ]